# Generated by Django 5.1.2 on 2024-11-03 00:49

import apps.gallery.models
import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display', models.BooleanField(default=True, help_text='Display this project in website gallery')),
                ('available_for_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.color')),
                ('type', models.ManyToManyField(to='gallery.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_image', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('description', models.CharField(help_text='3-5 words describing the image', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='description', unique_with=('fk_project',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=apps.gallery.models.get_image_path)),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.project')),
            ],
        ),
    ]
