# Generated by Django 5.1.2 on 2024-11-04 00:09

import apps.gallery.models
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('display', models.BooleanField(default=True, help_text='Display this product in website gallery')),
                ('available_for_sale', models.BooleanField(default=False)),
                ('add_to_shopify', models.BooleanField(default=False)),
                ('primary_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.color')),
                ('type', models.ManyToManyField(to='gallery.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_image', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('description', models.CharField(help_text='3-5 words describing the image', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='description', unique_with=('fk_product',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=apps.gallery.models.get_image_path)),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.product')),
            ],
        ),
    ]
