# Generated by Django 5.1.2 on 2024-11-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=True, help_text='Enable to display this product on the Homepage as a featured product.', verbose_name='Enable Featured Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, help_text='Enable to display this product in Site Gallery', verbose_name='Enable Gallery Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_sync',
            field=models.BooleanField(default=False, help_text="Enable to sync this product with Shopify Admin and make it available via the Shopify Online Store and Shopify POS. Please note, updates made via Shopify Admin will be overridden, and do not sync with this site's product database. A Shopify Access Token is required!", verbose_name='Enable ShopSync'),
        ),
    ]
