# Generated by Django 5.1.2 on 2024-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, help_text='If selected, this product will be displayed in Site Gallery', verbose_name='Gallery Display Enabled'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_sync',
            field=models.BooleanField(default=False, help_text="If selected, this product's data will synced with Shopify and available via the Shopify Online Store and Shopify POS. Please note, updates made via Shopify Admin will be overridden, and do not sync with this site.", verbose_name='Shopify Sync Enabled'),
        ),
    ]
