# Generated by Django 5.1.2 on 2024-11-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_product_display_alter_product_shop_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sync_error',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sync_error_msg',
        ),
    ]
