# Generated by Django 5.1.6 on 2025-02-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_remove_product_price_remove_product_primary_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="original",
        ),
    ]
