# Generated by Django 5.1.2 on 2024-12-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_productvariant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.product'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.productoption', verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.product'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Option Value'),
        ),
    ]
