# Generated by Django 5.1.2 on 2025-01-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_productoption_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptionvalue',
            old_name='name',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='shopify_id',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters')], default='IN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_unit',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters')], default='IN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('LB', 'Pounds'), ('OZ', 'Ounces'), ('G', 'Grams'), ('KG', 'Kilograms')], default='OZ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_unit',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters')], default='IN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='oh_quantity',
            field=models.IntegerField(default=1, verbose_name='On Hand Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=True, help_text='Enable to display on the Homepage as a featured product.', verbose_name='Enable Featured Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='Item base price. Variant pricing will override this.', null=True, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Enable to display this product in Site Gallery', max_length=10, verbose_name='Add to Gallery'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='feature_image',
            field=models.BooleanField(default=False, help_text="Enable to display this image as the featured image. The featured image is used as the product's primary image. Only select this for one image per product."),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='values',
            field=models.ManyToManyField(blank=True, help_text='Values for this Option (e.g. "Red", "Blue", etc.', to='gallery.productoptionvalue', verbose_name='Option Values'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='inv_policy',
            field=models.CharField(choices=[('DENY', 'Deny'), ('CONTINUE', 'Continue')], default='DENY', help_text='When a product has no inventory available, this policy determines if new orders should continue to process, or be denied.', max_length=100, verbose_name='Inventory Policy'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=0, verbose_name='Variant Price'),
        ),
    ]
