# Generated by Django 5.1.6 on 2025-02-17 20:59

from django.db import migrations, models

import apps.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_productimage_original_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="original",
            field=models.ImageField(
                height_field="original_height",
                upload_to=apps.gallery.models.get_image_path,
                verbose_name="image",
                width_field="original_width",
            ),
        ),
    ]
