# Generated by Django 5.1.2 on 2025-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_name_productoptionvalue_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_global_id',
            field=models.CharField(blank=True, editable=False, help_text='Shopify Global productID', max_length=100, null=True),
        ),
    ]
