# Generated by Django 5.1.2 on 2025-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_product_shopify_global_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.FloatField(blank=True, default=0, help_text='Variant pricing will override this.', null=True),
        ),
    ]
