# Generated by Django 5.1.2 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_GID',
            field=models.CharField(blank=True, help_text='Shopify productID', max_length=100),
        ),
    ]
