# Generated by Django 5.1.2 on 2024-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_product_shop_gid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_to_shopify',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_for_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_sync',
            field=models.BooleanField(default=False, help_text="If selected, this product's data will synced with Shopify and available via the Shopify Online Store and Shopify POS. Please note, updates made via Shopify Admin will be overridden, and do not sync withthis site."),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, help_text='Enter price', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_GID',
            field=models.CharField(blank=True, editable=False, help_text='Shopify Global productID', max_length=100),
        ),
    ]
