# Generated by Django 5.1.2 on 2024-11-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_product_add_to_shopify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, help_text='If selected, this product will be displayed in Site Gallery'),
        ),
    ]
