# Generated by Django 5.1.2 on 2024-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_product_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, help_text="If item is not synced with Shopify, enter price as '0'."),
        ),
    ]
