# Generated by Django 5.1.2 on 2024-11-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_GID',
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_global_id',
            field=models.CharField(blank=True, editable=False, help_text='Shopify Global productID', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10),
        ),
    ]
