# Generated by Django 5.1.2 on 2025-01-08 01:31

import apps.main.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='3-5 words describing the image', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='description', unique_with=('fk_product',))),
                ('image', models.ImageField(upload_to=apps.main.models._get_image_path)),
            ],
        ),
    ]
